name: "Test"

on:
  # TODO: move to "main" branch
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  run:
    name: "Go"
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v4

    - name: "Setup Go"
      uses: actions/setup-go@v4
      with:
        go-version-file: "go.mod"

    - name: "Build"
      run: |
        go build -v ./...

    - name: "Test"
      run: |
        go test -v ./...
 